persistence true
persistence_location /mosquitto/data/
log_dest stdout
log_type error
log_type warning
log_type notice
log_type information
connection_messages true
log_timestamp true

allow_anonymous false

# Dynamic Security plugin (oficial, substitui passwd/acl estáticos)
plugin /usr/lib/mosquitto_dynamic_security.so
plugin_opt_config_file /mosquitto/data/dynamic-security.json

# Listener 1: MQTT/TLS (ESP32, Node-RED externo)
listener 8883
protocol mqtt
cafile /etc/letsencrypt/live/hub.xtconect.online/chain.pem
certfile /etc/letsencrypt/live/hub.xtconect.online/cert.pem
keyfile /etc/letsencrypt/live/hub.xtconect.online/privkey.pem
tls_version tlsv1.2
require_certificate false

# Listener 2: MQTT/WSS (app web no browser)
listener 8884
protocol websockets
cafile /etc/letsencrypt/live/hub.xtconect.online/chain.pem
certfile /etc/letsencrypt/live/hub.xtconect.online/cert.pem
keyfile /etc/letsencrypt/live/hub.xtconect.online/privkey.pem
tls_version tlsv1.2

# Listener 3: MQTT plain INTERNO (rede docker xtnet, não exposto no host)
listener 1883
protocol mqtt
